In [10]:
# material from https://www.kaggle.com/kanncaa1/pytorch-tutorial-for-deep-learning-lovers
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import torch
print(os.listdir("/"))
!pwd

['home', 'usr', '.DS_Store', 'bin', 'sbin', '.file', 'etc', 'var', 'Library', 'System', '.VolumeIcon.icns', '.fseventsd', 'private', '.vol', 'Users', 'Applications', 'opt', 'dev', 'Volumes', 'tmp', 'cores']
/Users/marcochan/Desktop/NLP/notebooks


In [14]:
array = np.array([[1,2,3], [4,5,6]])
print(type(array))
tensor = torch.tensor(array)
print(type(tensor))
a = torch.ones((2,3))  # note parentheses or no parenthessi has hte same results
b  = torch.rand(2,3)   # no parentheses
print(a, '\n', b)

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
 tensor([[0.0240, 0.1074, 0.3058],
        [0.7881, 0.1872, 0.8020]])


In [18]:
# usuauly convert from tensor to numpy for analysis and plotting
tensor = torch.from_numpy(array)
print(tensor, type(tensor))

array = tensor.numpy()
print(array, type(array))

tensor([[1, 2, 3],
        [4, 5, 6]]) <class 'torch.Tensor'>
[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


In [26]:
# math
a = torch.ones(3,3)
b = a.view(9)
print(b, b.shape)

print('Addition: {} \n'.format(torch.add(a, a)))
print('Sub: {} \n'.format(torch.sub(a, a)))
print('mul: {} \n'.format(torch.mul(a, a)))
print('div: {} \n'.format(torch.div(a, a)))

print('mean: {} \n'.format(a.mean()))
print('std {} \n'.format(a.std()))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.]) torch.Size([9])
Addition: tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]) 

Sub: tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 

mul: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

div: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

mean: 1.0 

std 0.0 



In [31]:
# variables, store gradient, only difference between variables and tensor

from torch.autograd import Variable
var = Variable(torch.ones(3), requires_grad=True)
x = Variable(torch.Tensor([2, 4]), requires_grad = True)
y = x**2
print(y)
o = 1/2 * sum(y)
print(o)
o.backward() # calculate gradient
print(x.grad)

tensor([ 4., 16.], grad_fn=<PowBackward0>)
tensor(10., grad_fn=<MulBackward0>)
tensor([2., 4.])


In [ ]:
# Deep learning model torch implementation examples

train = pd.read_csv(r"../input/train.csv",dtype = np.float32)

# split data into features(pixels) and labels(numbers from 0 to 9)
targets_numpy = train.label.values
features_numpy = train.loc[:,train.columns != "label"].values/255 # normalization

# train test split. Size of train data is 80% and size of test data is 20%. 
features_train, features_test, targets_train, targets_test = train_test_split(features_numpy,
                                                                             targets_numpy,
                                                                             test_size = 0.2,
                                                                             random_state = 42) 

# create feature and targets tensor for train set. 
# As you remember we need variable to accumulate gradients. Therefore first we create tensor, then we will create variable
featuresTrain = torch.from_numpy(features_train)
targetsTrain = torch.from_numpy(targets_train).type(torch.LongTensor) # data type is long

# create feature and targets tensor for test set.
featuresTest = torch.from_numpy(features_test)
targetsTest = torch.from_numpy(targets_test).type(torch.LongTensor) # data type is long

# create feature and targets tensor for train set. As you remember we need variable to accumulate gradients. Therefore first we create tensor, then we will create variable
featuresTrain = torch.from_numpy(features_train)
targetsTrain = torch.from_numpy(targets_train).type(torch.LongTensor) # data type is long

# create feature and targets tensor for test set.
featuresTest = torch.from_numpy(features_test)
targetsTest = torch.from_numpy(targets_test).type(torch.LongTensor) # data type is long



# batch_size, epoch and iteration
batch_size = 100
n_iters = 10000
num_epochs = n_iters / (len(features_train) / batch_size)
num_epochs = int(num_epochs)

# Pytorch train and test sets
train = torch.utils.data.TensorDataset(featuresTrain,targetsTrain)
test = torch.utils.data.TensorDataset(featuresTest,targetsTest)

# data loader
train_loader = DataLoader(train, batch_size = batch_size, shuffle = False)
test_loader = DataLoader(test, batch_size = batch_size, shuffle = False)

# visualize one of the images in data set
plt.imshow(features_numpy[10].reshape(28,28))
plt.axis("off")
plt.title(str(targets_numpy[10]))
plt.savefig('graph.png')
plt.show()

# in the model before training, convert input into Variable   e.g.
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_loader):
        
        # Define variables
        train = train.to(device)
        labels = labels.to(device)
        
        # Clear gradients
        optimizer.zero_grad()
        
        # Forward propagation
        outputs = model(train)
        
        # Calculate softmax and cross entropy loss
        loss = error(outputs, labels)
        
        # Calculate gradients
        loss.backward()
        # Update parameters
        optimizer.step()